### ISSUE TITLE
0.22-stable version

### ISSUE THREAD

**Issue by shirgoldbird** [mainio/decidim-module-plans#43]
Could you create a 0.22-stable tag? I've been trying to install this gem, but can't find a tag, branch, or ref that works with Decidim 0.22. I keep getting this dependency error:

```
Bundler could not find compatible versions for gem "graphql":
  In snapshot (Gemfile.lock):
    graphql (= 1.11.5)

  In Gemfile:
    decidim-dev (= 0.22.0) was resolved to 0.22.0, which depends on
      decidim (= 0.22.0) was resolved to 0.22.0, which depends on
        decidim-api (= 0.22.0) was resolved to 0.22.0, which depends on
          graphql (~> 1.9)

    decidim-plans was resolved to 0.22.0, which depends on
      graphql (~> 1.9.19)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.```

**Comment by MohammedSalahadin** [comment]
I really hate this error, why they don't fix it?
this error is facing me in most of the models.
Running `bundle update` doesn't solve anything rather than updating all gems versions together.

**Comment by ahukkanen** [comment]
The module has been updated up to 0.27 version of core, so you can find the branch versions from GitHub for each Decidim release:
- release/0.23-stable
- release/0.24-stable
- release/0.25-stable
- release/0.26-stable
- master - For version 0.27 (currently)
